# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Java Code House
email: dilini.javacodehouse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Java code house is a resource for developers to learn and share emerging technologies in the software development field.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://javacodehouse.com" # the base hostname & protocol for your site
twitter_username: sewdil
github_username:  DiliniRajapaksha
twitter:
  username: sewdil
logo: /assets/img/logo.png
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji
permalink: /:categories/:title/

course-url: /courses/spring-boot/

general_mailmunch_popup: mailmunch-pop-747983

future: false

timezone: Australia/Melbourne

author: Dilini Rajapaksha
author-link: https://www.linkedin.com/in/dilinirajapaksha